cmake_minimum_required(VERSION 3.7)
project(Icarus)

if(APPLE)
	set(PLATFORM "macOS")
	set(CMAKE_CXX_COMPILER "clang++")
	set(ONNX_LIB_EXT "dylib")
	set(THREAD_LIB "")
elseif(UNIX AND NOT APPLE)
	set(PLATFORM "Linux")
	set(CMAKE_CXX_COMPILER g++-9)
	set(ONNX_LIB_EXT "so")
	set(THREAD_LIB "pthread")
elseif(WIN32)
	message(WARNING "Platform is not yet tested you may encounter issues")
	set(PLATFORM "Windows")
	set(CMAKE_CXX_COMPILER "g++")
	set(ONNX_LIB_EXT "dll")
	set(THREAD_LIB "")
else()
	message(FATAL_ERROR "Unsupported platform!")
endif()

message(STATUS "Building ${CMAKE_PROJECT_NAME} for ${PLATFORM}")

set(CXX_FLAGS "-Wall -g -Og")
set(CMAKE_CXX_FLAGS, "${CXX_FLAGS}")
set(CMAKE_BUILD_TYPE Debug)

add_library(onnxruntime SHARED IMPORTED)

set_target_properties(onnxruntime PROPERTIES IMPORTED_LOCATION ${CMAKE_SOURCE_DIR}/thirdparty/onnxruntime/lib/libonnxruntime.${ONNX_LIB_EXT})
target_include_directories(onnxruntime INTERFACE thirdparty/onnxruntime/include)

find_package(OpenCV 4 REQUIRED)

add_executable(Icarus src/main.cpp src/image_provider.cpp src/image_preprocessor.cpp src/model_handler.cpp src/runtime.cpp)
set_property(TARGET Icarus PROPERTY CXX_STANDARD 17)
target_include_directories(Icarus PRIVATE ${OpenCV_INCLUDE_DIRS} src)
target_link_libraries(Icarus onnxruntime ${OpenCV_LIBS} ${THREAD_LIB})
